modLoader = "javafml"
loaderVersion = "${neoforge_version_range}"
license = "${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "https://updates.blamejared.com/get?n=${mod_id}&gv=${minecraft_version}&ml=neoforge"
displayURL = "${mod_homepage}"
logoFile = "logo.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! ${mod_supporters}"
authors = "${mod_author}"
itemIcon = "minecraft:bookshelf"
description = '''
${mod_description}
'''

[[mixins]]
config = "${mod_id}.common.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"