modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Bookshelf/issues"

[[mods]]
modId = "bookshelf"
version = "26.2.0.0"
displayName = "Bookshelf"
updateJSONURL = "https://updates.blamejared.com/get?n=bookshelf&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/bookshelf"
logoFile = "logo_bookshelf.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Bookshelf is a library mod that provides code, frameworks, and utilities for other mods. Many mods make use of Bookshelf and are powered by its code."

[[mixins]]
config = "bookshelf.common.mixins.json"

[[mixins]]
config = "bookshelf.neoforge.mixins.json"

[[dependencies.bookshelf]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.bookshelf]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

